schemaVersion: 2.2.0
metadata:
  name: theia-next-external-dwoc
attributes:
  controller.devfile.io/storage-type: common
  controller.devfile.io/devworkspace-config:
    name: external-dwoc-storageaccess-rwx
    namespace: openshift-operators
projects:
  - name: devspaces-test-reproducer
    git:
      remotes:
        origin: https://github.com/rohankanojia-demos/devspaces-test-reproducer.git
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryLimit: 256Mi
      mountSources: true
commands:
  - id: say-hello
    exec:
      component: tools
      commandLine: echo "Hello world"
      workingDir: /
      group:
        kind: run
